### ISSUE TITLE
Add option : use let and const instead of var

### ISSUE THREAD

**Issue by tag9724** [vihanb/babel-plugin-loop-optimizer#3]
Hello.
The idea is to add an option for using const and let statements instead of var like this

**Before**

```JS
function timesTwo(arr) {
    var _a = arr;
    var _f = n => n * 2;
    var _r = [];

    for (var _i = 0; _i < _a.length; _i++)
        _r.push(_f(_a[_i], _i, _a));

    return _r;
}
```

**After** 

```JS
function timesTwo(arr) {
    const _a = arr;
    const _f = n => n * 2;
    const _r = [];

    for (let _i = 0, len = _a.length; _i < len; _i++)
        _r.push(_f(_a[_i], _i, _a));

    return _r;
}
```

**Comment by vihanb** [comment]
I don't think this is really necessary for two reasons:

 - `let`: we don't need to replace with let because babel will automatically generate a unique identifier
 - `const`: because this is a unique identifier, it will only be used by the plugin and mutated as it is supposed to.

Also it doesn't serve any documenting purposes/etc. because the generated code is not even supposed to be read anyway.
